# Generated by Django 2.2.8 on 2020-02-13 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200213_1410'),
        ('submit_essay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writeessay',
            name='user',
        ),
        migrations.AddField(
            model_name='writeessay',
            name='detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile'),
        ),
    ]
