# Generated by Django 2.2.8 on 2020-02-13 08:52

from django.db import migrations, models
import submit_essay.validators


class Migration(migrations.Migration):

    dependencies = [
        ('submit_essay', '0002_auto_20200213_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writeessay',
            name='essay_text',
            field=models.TextField(validators=[submit_essay.validators.CheckEssayText]),
        ),
    ]
